; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=useless Platformer game
AppVersion=1.5
DefaultGroupName=Toxik Devs
DefaultDirName={autopf}\Game
[Files]
Source: "Game.exe"; DestDir: "{app}"
Source: "*"; DestDir: "{app}"